stages: [build, test, release]

#include:
#  - component: ${CI_SERVER_FQDN}/${CI_PROJECT_PATH}/test:codeception:acceptance@$CI_COMMIT_SHA
#  - component: ${CI_SERVER_FQDN}/${CI_PROJECT_PATH}/test:codeception:@$CI_COMMIT_SHA

include:
  - component: ${CI_SERVER_FQDN}/devops/ci-cd-components/release-tools/semantic-release@1.7.0
    inputs:
      stage: release

#create-release:
#  stage: release
#  image: registry.moselwal.io/devops/release-cli/release-cli:latest
#  rules:
#    - if: $CI_COMMIT_TAG
#  script: echo "Creating release $CI_COMMIT_TAG"
#  release:
#    tag_name: $CI_COMMIT_TAG
#    description: "Release $CI_COMMIT_TAG of components repository $CI_PROJECT_PATH"
